version: '3'

services:
  web:
    image: gorm2303/ba-web-application:latest
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=http://cacher-api:8080/videometadata
    depends_on:
      - uploader
      - redis

  uploader:
    image: gorm2303/ba-video-uploader:latest
    ports:
      - "80:80"
    volumes:
      - video_data:/app/data

  reader:
    image: gorm2303/ba-video-reader:latest
    ports:
      - "8000:8000"
    volumes:
      - video_data:/app/data

  cacher-api:
    image: gorm2303/ba-video-cacher:latest
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - VIDEOS_URL=http://reader:8000/videos
      - VIDEO_URL=http://reader:8000/videos/{id}
    depends_on:
      - redis
      - reader
  
  redis:
    image: redis:7.0.9-alpine
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

volumes:
  video_data:
  redis_data:

