version: '3'

services:
  web:
    image: gorm2303/ba-web-application:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      - REACT_APP_CACHER_VIDEOMETADATA_URL=http://localhost:8000/videometadata
      - REACT_APP_UPLOADER_URL=http://localhost:8080/api/v1/
      - REACT_APP_UPLOADER_VIDEOMETADATA_URL=http://localhost:8080/api/v1/videometadata
    depends_on:
      - uploader
      - cacher-api
    volumes:
      - video_data:/app/public/app/data

  uploader:
    image: gorm2303/ba-video-uploader:latest
    ports:
      - "8080:8080"
    volumes:
      - video_data:/app/data

  reader:
    image: gorm2303/ba-video-reader:latest
    ports:
      - "5000:5000"
    volumes:
      - video_data:/app/data

  cacher-api:
    image: gorm2303/ba-video-cacher:latest
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - VIDEOS_URL=http://reader:5000/videos
      - VIDEO_URL=http://reader:5000/videos/{id}
    depends_on:
      - redis
      - reader
  
  redis:
    image: redis:7.0.9-alpine
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongodb
    volumes:
      - mongodb-volume:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: video_db


volumes:
  video_data:
  redis_data:
  mongodb-volume:

