apiVersion: v1
kind: Service
metadata:
  name: mongo-users
spec:
  clusterIP: None
  selector:
    app: mongo-users
  ports:
    - protocol: TCP
      port: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-users
spec:
  serviceName: mongo-users
  replicas: 3
  selector:
    matchLabels:
      app: mongo-users
  template:
    metadata:
      labels:
        app: mongo-users
    spec:
      containers:
      - name: mongo-users
        image: mongo:latest
        command:
          - mongod
          - "--replSet"
          - rs0
          - "--bind_ip"
          - 0.0.0.0
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-users-data
          mountPath: /data/db
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
  volumeClaimTemplates:
    - metadata:
        name: mongo-users-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi